import turtle
def END_GAME():
    turtle.title("End Game")
    turtle.speed(2)
    turtle.fillcolor("Red")
    turtle.pencolor("White")
    turtle.shape("turtle")
    turtle.pensize(5)
    turtle.left(90)
    turtle.left(90)
    turtle.forward(400)
    turtle.clear()
    turtle.right(90)
    def E():
        turtle.pen(pencolor='green',pensize=5,fillcolor='Yellow',speed=2)
        turtle.forward(70)
        turtle.right(90)
        turtle.forward(75)
        turtle.right(180)
        turtle.forward(75)
        turtle.left(90)
        turtle.forward(85)
        turtle.left(90)
        turtle.forward(75)
        turtle.right(180)
        turtle.forward(75)
        turtle.left(90)
        turtle.forward(85)
        turtle.left(90)
        turtle.forward(75)
    E()
    turtle.pencolor("White")
    turtle.forward(50)
    def N():
        turtle.pen(pencolor='Red', pensize=5, fillcolor='pink',speed=2)
        turtle.left(90)
        turtle.forward(170)
        turtle.goto(-200,0)
        turtle.forward(170)
    N()
    turtle.pencolor("White")
    turtle.right(90)
    turtle.forward(50)
    def D():
        turtle.pen(pencolor='pink', pensize=5, fillcolor='blue',speed=2)
        turtle.right(90)
        turtle.forward(170)
        turtle.goto(-80,75)
        turtle.goto(-150, 180)
    D()
    turtle.pencolor("White")
    turtle.left(90)
    turtle.forward(150)
    def G():
        turtle.pen(pencolor='orange', pensize=5, fillcolor='Green', speed=2)
        turtle.right(90)
        turtle.goto(-40,85)
        turtle.goto(0,0)
        turtle.goto(30, 85)
        turtle.right(90)
        turtle.forward(40)
        turtle.back(40)
    G()
    turtle.pencolor("White")
    turtle.goto(50,100)
    turtle.goto(50,0)
    turtle.left(180)
    turtle.forward(50)
    def A():
        turtle.pen(pencolor='violet', pensize=5, fillcolor='red', speed=2)
        turtle.goto(115,85)
        turtle.forward(30)
        turtle.back(30)
        turtle.goto(132, 170)
        turtle.goto(160, 0)
    A()
    turtle.pencolor("White")
    turtle.forward(50)
    def M():
        turtle.pen(pencolor='yellow', pensize=5, fillcolor='brown', speed=2)
        turtle.left(90)
        turtle.forward(170)
        turtle.goto(250,85)
        turtle.goto(290, 170)
        turtle.left(180)
        turtle.forward(170)
    M()
    turtle.pencolor("White")
    turtle.left(90)
    turtle.forward(50)
    def E1():
        turtle.pen(pencolor='magenta', pensize=5, fillcolor='yellow', speed=2)
        turtle.left(90)
        turtle.forward(170)
        turtle.right(90)
        turtle.forward(75)
        turtle.right(180)
        turtle.forward(75)
        turtle.left(90)
        turtle.forward(85)
        turtle.left(90)
        turtle.forward(75)
        turtle.right(180)
        turtle.forward(75)
        turtle.left(90)
        turtle.forward(85)
        turtle.left(90)
        turtle.forward(75)
    E1()